### ISSUE TITLE
Overlap TCGA samples

### ISSUE THREAD

**Issue by vittoriofortino84** [waldronlab/curatedTCGAData#30]
Hi,
the overlap of TCGA-BRCA sample patients is very poor when considering mRNA, miRNA-seq and methylation profiles, and the PAM50 subtypes (58 patients). So, could you please provide an example about how to build a multi-omics dataset by using the curatedTCGAData package?

Thank you for your help and support.
Br,
Vittorio

**Comment by LiNk-NY** [comment]
Hi Vittorio, @vittoriofortino84 

Sorry I didn't see your message. Please use my username tag so that I get a notification (@LiNk-NY).
This question is best answered on the Bioconductor support site. If you can post it there, I will follow up. 
GitHub issues are more for reporting bugs or questions about the software implementation. 

Best,
Marcel
