### ISSUE TITLE
error message in curatedTCGAData for retrieving TCGA data

### ISSUE THREAD

**Issue by llusayl** [waldronlab/curatedTCGAData#41]
Today I used curatedTCGAData in extracting data from TCGA datasets, which usually works properly, an error message came out as: 
library(curatedTCGAData)
paad <- curatedTCGAData(diseaseCode = "PAAD", assays="RNASeq2GeneNorm", dry.run=F)

Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "c('tbl_SQLiteConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"
In addition: Warning messages:
1: `select_()` is deprecated as of dplyr 0.7.0.
Please use `select()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
2: `filter_()` is deprecated as of dplyr 0.7.0.
Please use `filter()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.

Not quite sure what problem occurs here. 

Thanks in advance.

**Comment by LiNk-NY** [comment]
Please provide a reproducible example
Can you provide more information as to what version of Bioconductor are you using? 
This works for me on Bioc 3.12 and Bioc-devel. 

``` r
suppressPackageStartupMessages({
    library(curatedTCGAData)
})
curatedTCGAData(
    diseaseCode = "PAAD", assays="RNASeq2GeneNorm", dry.run=FALSE
)
#> snapshotDate(): 2020-10-02
#> Working on: PAAD_RNASeq2GeneNorm-20160128
#> see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
#> loading from cache
#> Working on: PAAD_colData-20160128
#> see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
#> loading from cache
#> Working on: PAAD_metadata-20160128
#> see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
#> loading from cache
#> Working on: PAAD_sampleMap-20160128
#> see ?curatedTCGAData and browseVignettes('curatedTCGAData') for documentation
#> loading from cache
#> harmonizing input:
#>   removing 1936 sampleMap rows not in names(experiments)
#>   removing 7 colData rownames not in sampleMap 'primary'
#> A MultiAssayExperiment object of 1 listed
#>  experiment with a user-defined name and respective class.
#>  Containing an ExperimentList class object of length 1:
#>  [1] PAAD_RNASeq2GeneNorm-20160128: SummarizedExperiment with 20501 rows and 183 columns
#> Functionality:
#>  experiments() - obtain the ExperimentList instance
#>  colData() - the primary/phenotype DataFrame
#>  sampleMap() - the sample coordination DataFrame
#>  `$`, `[`, `[[` - extract colData columns, subset, or experiment
#>  *Format() - convert into a long or wide DataFrame
#>  assays() - convert ExperimentList to a SimpleList of matrices
#>  exportClass() - save all data to files
BiocManager::version()
#> [1] '3.12'
BiocManager::valid()
#> [1] TRUE
```

<sup>Created on 2020-11-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by llusayl** [comment]
Thank you. It is BioC version (3.10), when I used BiocManager::version(), is it correct? my R is 3.6.2.  
Really surprising is in my office computer, it works. However, in my laptop, it used to work properly at least a week ago.

**Comment by LiNk-NY** [comment]
@llusayl 
We recommend that you use the latest version of Bioconductor (v 3.12) with R version `>= 4.0.2`. Although you have an older version of Bioconductor, the CRAN packages may be newer than the ones used to build the older version of Bioconductor (note. we are working on providing CRAN snapshots) and thus may be causing issues.

**Comment by lwaldron** [comment]
Yes, agreed with @LiNk-NY.  Just to add that errors like:
```r
Error in UseMethod("filter_") :
no applicable method for 'filter_' applied to an object of class "c('tbl_SQLiteConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"
```

Typically mean that the function throwing the error (`filter_`) is has been "over-written" (given precedent in the namespace) by another package loaded afterwards. There's no useage of `filter_` in the current version of MultiAssayExperiment or curatedTCGAData, so I suspect it's some combination of the usage of old software and loading other packages after curatedTCGAData. If you want to keep running the older software, you might be able to fix this particular problem by loading fewer packages or changing the order in which you load them, in particular loading dplyr (and anything that depends on it, like tidyverse) last so that its namespace will take precedence. You can also type the function name of the function without parentheses to see which package is taking precedence in its definition. These namespace errors can seem like magic after you've added another `library()` command and suddenly previously working code doesn't work any more because your namespace is changed.

**Comment by llusayl** [comment]
Thank you both very much. I will update my R.  Stay well.

**Comment by LiNk-NY** [comment]
Happy to help! Stay healthy and safe!
